import Head from 'next/head'
import LoginForm from "@/components/Login/LoginForm";

export default function Home() {
  return (
      <>
        <Head>
          <title>Authentication</title>
          <meta name="description" content="Generated by create next app"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <LoginForm/>
      </>
  )
}
